#This workflow will do an installation of node dependencies and run the automated robotframework tests with the selenium library

name: Robot Framework CI

on:
    push:
        branches: [ "integration" ]
    pull_request:
        branches: [ "integration" ]

jobs:
    robotframework:
        runs-on: ubuntu-latest
        strategy:
            matrix:
              node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
                cache: 'npm'
            - run: npm install
            - run: npm run test
            - run: npm run run
            # live server now running, run the robot tests
            - run: npm run robot
