name: Robot Framework - Python
on:
  push:
    branches: [ "integration" ]
  pull_request:
    branches: [ "integration" ]

permissions:
  contents: read


jobs:
  robot_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Robot Framework
        uses: tarathep/robotframework-github-action@v1.0
        with:
          image: kietara/robot-framework
          image_version: 1.0
          tests_dir: '${{ github.workspace }}/__test__/'
          reports_dir: '${{ github.workspace }}/__test__/output/'
